{% set name = "globus-automate-client" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e7d3133fdc8582c28bf14b3d2ee0dfd49944dc4c43b8c1e0466d71d756ff1b9f

build:
  entry_points:
    - globus-automate = globus_automate_client.cli.main:app
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6.3,<4.0.0
    - poetry >=0.12
  run:
    - arrow >=1.1.1,<2.0.0
    - globus-sdk >=3.1,<4.0
    - python-graphviz >=0.12,<0.13
    - importlib-metadata >=4.8.1,<5.0.0
    - jsonschema >=3.2.0,<4.0.0
    - python >=3.6.3,<4.0.0
    - pyyaml >=5.3.1,<6.0.0
    - rich >=12.3.0,<13.0.0
    - typer >=0.4.1,<0.5.0
    - typing-extensions >=4.1.1,<5.0.0

test:
  imports:
    - globus_automate_client
  commands:
    - pip check
    - globus-automate --help
  requires:
    - pip

about:
  home: https://pypi.org/project/globus-automate-client/
  summary: Client for the Globus Flows service
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - carterbox
    - AdvancedPhotonSource/ptychodus
