{% set name = "globus-automate-client" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/d5/2a/6d18c6ab5d8b745329aaf96c8f1c8fb595efaba40b951578beecfcb0d43a/globus_automate_client-{{ version }}.tar.gz
  sha256: a07c3c676dbb5480a510e51f9ee10dc641ba4464d058abc8aa9df8dfed6d3911

build:
  entry_points:
    - globus-automate = globus_automate_client.cli.main:app
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6.3,<4.0.0
    - poetry >=1.0.0
  run:
    - arrow >=1.1.1,<2.0.0
    - globus-sdk >=3.1,<4.0
    - python-graphviz >=0.12,<0.13
    - importlib-metadata >=4.8.1,<5.0.0
    - jsonschema >=3.2.0,<4.0.0
    - python >=3.6.3,<4.0.0
    - pyyaml >=6.0.1,<7.0.0
    - rich >=12.3.0,<13.0.0
    - typer >=0.4.1,<0.5.0
    - typing-extensions >=4.1.1,<5.0.0

test:
  imports:
    - globus_automate_client
  commands:
    - pip check
    - globus-automate --help
  requires:
    - pip

about:
  home: https://pypi.org/project/globus-automate-client/
  summary: Client for the Globus Flows service
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - carterbox
    - AdvancedPhotonSource/ptychodus
